import time
from typing import Dict, Any, Optional, Callable
from app.agents.base import (
    BaseGeneratorAgent,
    GeneratorConfig,
    GeneratorResult,
    GeneratedTestFile,
)


def _slugify(title: str) -> str:
    return "".join(c.lower() if c.isalnum() else "_" for c in title).strip("_")


class MockGeneratorAgent(BaseGeneratorAgent):
    """
    Stage 2 Mock Generator Agent.
    Simulates converting plan scenarios into executable Playwright test files with live
    selector/assertion validation, one spec file per scenario.
    """

    def generate(
        self,
        config: GeneratorConfig,
        log_callback: Callable[[str, str, Optional[Dict[str, Any]]], None],
        cancel_check: Optional[Callable[[], bool]] = None,
    ) -> GeneratorResult:
        def check_cancelled():
            if cancel_check and cancel_check():
                log_callback("WARN", "Generation cancelled by user request.", None)
                return True
            return False

        scenarios = config.plan.get("scenarios", [])
        log_callback("INFO", f"Generator Agent starting: converting {len(scenarios)} scenarios into executable tests.", None)
        time.sleep(0.3)
        if check_cancelled():
            return GeneratorResult(status="failed", error_message="cancelled")

        files = []
        validation_report = {}

        for scenario in scenarios:
            if check_cancelled():
                return GeneratorResult(status="failed", error_message="cancelled")

            title = scenario.get("title", "scenario")
            test_case_id = scenario.get("id") or scenario.get("test_case_id")
            slug = _slugify(title)
            relative_path = f"tests/test_{slug}.spec.py"
            func_name = f"test_{slug}"

            log_callback("INFO", f"Validating selectors for scenario: {title}", {"scenario": title})
            time.sleep(0.2)

            steps = scenario.get("steps", [])
            step_lines = []
            for step in steps:
                action = step.get("action", "Navigate")
                target = step.get("target_element") or "body"
                step_lines.append(f'    # {action} on {target}')
                if action.lower() == "navigate":
                    step_lines.append(f'    page.goto(TARGET_URL + "{target}")' if target.startswith("/") else f'    page.goto(TARGET_URL)')
                elif action.lower() == "fill":
                    step_lines.append(f'    page.fill("{target}", "test_value")')
                elif action.lower() == "click":
                    step_lines.append(f'    page.click("{target}")')
                elif action.lower() == "assert":
                    step_lines.append(f'    expect(page.locator("{target}")).to_be_visible()')
            body = "\n".join(step_lines) if step_lines else "    pass"

            content = f'''"""
Autonomous Generated Playwright Test: {title}
Category: {scenario.get("category", "happy_path")}
Generated by Aitesty Generator Agent
"""
from playwright.sync_api import Page, expect

TARGET_URL = "{config.target_url}"

def {func_name}(page: Page):
    """{scenario.get("description", title)}"""
{body}
'''
            files.append(GeneratedTestFile(
                relative_path=relative_path,
                content=content,
                covers_test_case_ids=[test_case_id] if test_case_id else [],
            ))
            validation_report[title] = {"selectors_validated": True, "issues": []}

        log_callback("INFO", f"Generation complete. Produced {len(files)} test file(s).", {"files": [f.relative_path for f in files]})

        return GeneratorResult(
            status="success",
            files=files,
            validation_report=validation_report,
        )
